version: '3'

services:
  neo4j:
    image: neo4j:latest
    container_name: gnuploader_neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - gnuploader_neo4j-data:/data
    environment:
      NEO4J_AUTH: neo4j/secret_password # change here!
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
      NEO4J_dbms_security_procedures_whitelist: "apoc.*,gds.*"
    networks:
      - gnuploader_network


  nginx:
    image: nginx:latest
    container_name: gnuploader_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    depends_on:
      - neo4j
    networks:
      - gnuploader_network

networks:
  gnuploader_network:
    driver: bridge

volumes:
  gnuploader_neo4j-data:
